### ISSUE TITLE
Refactor BrowserWindow layout

### ISSUE THREAD

**Issue by tim-sueberkrueb** [lirios/browser#10]
- [x] Drop `DockCanvas`
- [x] ~~Elevate toolbar/expansion bar~~ By design: won't be elevated
- [x] New search bar
- [x] Denser layout
- [x] Improve Material Design compliance

**Comment by timsueberkrueb** [comment]
See [feature/refactor_browserwindow](https://github.com/lirios/browser/tree/feature/refactor_browserwindow).

**Comment by timsueberkrueb** [comment]
Done.
