### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by tim-sueberkrueb** [lirios/browser#2]
Introduce an initial set of configuration options (e.g. search engine).
Settings should be presented as tab page with the url `liri://settings`.
Consider supporting sub categories like `liri://settings/search-engine`.
Consider to support searching through the settings.
Initial settings should include:
* [x] start page (default: `start.liri.io`, `DuckDuckGo.com` or `Google.com`)
* [x] search engine (default: `DuckDuckGo` or `Google`)

**Comment by timsueberkrueb** [comment]
In progress in [feature/settings](https://github.com/lirios/browser/tree/feature/settings).

**Comment by timsueberkrueb** [comment]
Done. Settings will receive some further improvements (including breaking changes) before the initial release.
