### ISSUE TITLE
Can't open a url

### ISSUE THREAD

**Issue by c-cesar** [lirios/browser#23]
After writing any url in address field Liri Browser redirects to google home page. The only way to navigate is to search teh site in Google and click in the result.

**Comment by timsueberkrueb** [comment]
Hey, @c-cesar, thanks for reporting. This problem was confirmed by @Aldrog and [on G+](https://plus.google.com/u/0/+JohnPoison/posts/DoUic3QVnaA?cfem=1).

> It seems that editingFinished fires before accepted, resetting original text of TextField﻿

Unfortunately, I cannot reproduce this problem on Ubuntu 16.10, Unity 7. Contributions (via pull-request) are very welcome!

**Comment by timsueberkrueb** [comment]
Would changing 
```
onEditingFinished: {
    showUrlField.editActive = false;
}
```
to
```qml
onActiveFocusChanged: {
    if (!activeFocus) {
        showUrlField.editActive = false;
    }
}                
```
in [Omnibox.qml](https://github.com/lirios/browser/blob/develop/src/ui/omnibox/Omnibox.qml) fix the problem for you?

**Comment by timsueberkrueb** [comment]
@Aldrog confirmed the solution above via Slack confirmation.
