### ISSUE TITLE
Add Startpage.com to search pages

### ISSUE THREAD

**Issue by TheCom3di4n** [lirios/browser#32]
As the Liri Browser promotes its privacy, startpage.com should be added as one of the search pages delivered with installation. (IMHO) [Startpage](https://www.startpage.com) is one of the leading services in protecting the privacy of people. :+1:

**Comment by timsueberkrueb** [comment]
I just pushed an experimental extension for StartPage: https://github.com/tim-sueberkrueb/lbx-extras.

**Comment by timsueberkrueb** [comment]
Extensions support was dropped for now, so we might only support a certain set of search engines - at least for the first release(s).
