### ISSUE TITLE
"SlimeEngine" is not installed  ——archlinux

### ISSUE THREAD

**Issue by LoogCP** [lirios/browser#33]
QQmlApplicationEngine failed to load component
qrc:/ui/Main.qml:25 module "SlimeEngine" is not installed

Using QtWebEngine
fish: './liri-browser' terminated by signal SIGSEGV (Address boundary error)

**Comment by timsueberkrueb** [comment]
Hey @LCP199210. 
As described [in this part of the wiki](https://github.com/lirios/browser/wiki/Development-Setup), you need to setup `SlimeEngine` in order to run Liri Browser.
It looks like it's not installed. 
Otherwise, I need more information: What did you do, how did you build/install the browser?

**Comment by LoogCP** [comment]
There's no package named slimengine in pacman or yaourt(my os is arch).
I install qt5 first,sudo qmake .. CONFIG+=QTWEBENGINE_ENABLED, make , sudo
make install.
I cloud give more information but I shutdown my PC(11:17 in China).
Thinks!

2017年1月9日 下午11:07，"Tim Süberkrüb" <notifications@github.com>写道：

**Comment by timsueberkrueb** [comment]
@LCP199210 I don't know if anyone has packaged SlimeEngine for Arch. As I said, please look in the wiki link I pasted above. You will find detailed instructions about how do build and install SlimeEngine and the browser from source.

**Comment by Aldrog** [comment]
@LCP199210 @tim-sueberkrueb 
There's slime-engine-git package in the AUR. Seems up-to-date and is maintained by @plfiorini

**Comment by timsueberkrueb** [comment]
@Aldrog ah, awesome, thanks for the info :)

**Comment by timsueberkrueb** [comment]
After all, SlimeEngine is just a simple pure-QML wrapper to support both QtWebEngine and Oxide.

**Comment by timsueberkrueb** [comment]
Closing this. @LCP199210 if this didn't fix you issue, please feel free to reopen.
