### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by timsueberkrueb** [lirios/browser#38]

**Comment by PoisonousJohn** [comment]
Hey @tim-sueberkrueb !  Could you please add description of this issue? What should be included in this feature?

**Comment by timsueberkrueb** [comment]
Hey @JohnPoison, sure!
The following scenarios should be supported:
* User presses F11/Clicks on menu item "Fullscreen" to go in fullscreen mode
* A website (e.g. YouTube) requests fullscreen mode

In both cases, the window should [`showFullscreen`](https://doc.qt.io/qt-5/qml-qtquick-window-window.html#showFullScreen-method) and both omnibar and tabbar should only show up when the user hovers the cursor at the top of the screen. There should be no separate component like a fullscreen bar (as with the old version of Liri Browser). Nevertheless, in fullscreen mode there should be an [additional button](https://material.io/icons/#ic_fullscreen_exit) next to the menu button in the toolbar allowing to force exit fullscreen mode. Same should happen pressing ESC or F11 again.

For handling website fullscreen requests, see the [relevant SlimeEngine signal](https://github.com/tim-sueberkrueb/slime-engine/blob/master/modules/SlimeEngine/0.2/wrap/WebView.qml#L120).

**Comment by PoisonousJohn** [comment]
Job is done in #48

**Comment by timsueberkrueb** [comment]
Great, thank you!
