### ISSUE TITLE
Provide a Snap

### ISSUE THREAD

**Issue by timsueberkrueb** [lirios/browser#39]
Provide a [Snap package](http://snapcraft.io/) for the browser.
Things to consider:
* Oxide vs QtWebEngine
* Use [cloud part](https://github.com/tjyrinki/qt58) as reference.
* App platform snap (like `ubuntu-app-platform`) with Fluid and Qt 5.8?
  * Provide standalone and version based on app platform snap?
* Name: `liri-browser` vs `io.liri.browser`
* Store account management

**Comment by plfiorini** [comment]
I propose to go full QtWebEngine and even drop SlimeEngine if it's possible to have a platform snap with Qt 5.8.

**Comment by timsueberkrueb** [comment]
@plfiorini Yeah. I'd really like to get rid of SlimeEngine and use pure QtWebEngine when possible. Basically it has to ...
1. run fine on Mir
2. run fine on armhf devices
3. should not come with significant drawbacks related to platform integration (e.g. download handling on Ubuntu Touch [negligible though IMO]) and more important touch handling (e.g. text selection on touch devices)

**Comment by timsueberkrueb** [comment]
Status: 
* Building QtWebEngine using snapcraft ([snapcraft.yaml](http://paste.ubuntu.com/24078688/)) results in a [strage NSS error](http://paste.ubuntu.com/24089807/).
* [Oxide doesn't build against Qt 5.8, yet](https://bugs.launchpad.net/oxide/+bug/1669753).
* Running QtWebEngine inside a snap doesn't work with or without confinement (`devmode`):
   * without confinement: http://paste.ubuntu.com/24092589/

Help wanted!

**Comment by probonopd** [comment]
Would you be interested in an [AppImage](http://appimage.org/)? Shouldn't be too hard using [linuxdeployqt](https://github.com/probonopd/linuxdeployqt). Let me know if you'd like help.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by timsueberkrueb** [comment]
Hey @probonopd, thanks very much for offering your help! That's of course something worth looking into as well. I opened a [separate issue for this](https://github.com/lirios/browser/issues/44). Could you possibly copy your comment over there? Thanks :)
EDIT: copied your comment in the issue description.

**Comment by timsueberkrueb** [comment]
There's now [snap packaging for Liri Browser](https://github.com/lirios/snap-apps)! No package has yet been released to the store, though.
~EDIT: It also doesn't start, yet c:~

**Comment by timsueberkrueb** [comment]
It would make sense to move snap packaging to individual app repos (once functional like browser snap is) so we can get automatic builds via [build.snapcraft.io](https://build.snapcraft.io).
@plfiorini are you okay with that?

**Comment by plfiorini** [comment]
@tim-sueberkrueb ok

**Comment by timsueberkrueb** [comment]
WIP in `feature/snap`

**Comment by timsueberkrueb** [comment]
```
snap install --edge liri-browser
```
