### ISSUE TITLE
Roboto doesn't support some languages

### ISSUE THREAD

**Issue by eliza0x** [lirios/browser#41]
I want to changing default fonts. Default fonts can't displaying Japanese.

**Comment by timsueberkrueb** [comment]
Thanks for reporting @eliza0x. This is a bug.
The Noto font should be used for languages that Roboto doesn't support, including Chinese (simplified and traditional), Japanese, Korean, Thai and Hindi ([according to Wikipedia](https://en.wikipedia.org/wiki/Roboto#Language_coverage)).

**Comment by timsueberkrueb** [comment]
This is an upstream bug in QtQuick Controls 2: https://bugreports.qt.io/browse/QTBUG-59579. 
Thanks @Aldrog.

**Comment by Aldrog** [comment]
@eliza0x currently everything should work fine if you have Noto installed, but **not** Roboto

**Comment by eliza0x** [comment]
@Aldrog Installing Noto and solved problem. thank you. :smile:

**Comment by timsueberkrueb** [comment]
@eliza0x installing Noto alone solved the problem or did you have to uninstall Roboto?

**Comment by eliza0x** [comment]
@tim-sueberkrueb Installing Noto alone, I don't uninstall Roboto.

**Comment by timsueberkrueb** [comment]
@eliza0x is Roboto installed at all?

**Comment by eliza0x** [comment]
Sorry. not installed Roboto.

```
% fc-list | grep Roboto 
(No output)
```

**Comment by timsueberkrueb** [comment]
@eliza0x okay, thanks for the information.
