### ISSUE TITLE
QML import versions

### ISSUE THREAD

**Issue by timsueberkrueb** [lirios/browser#42]
QML import versions change frequently. Would it make sense to ...
* create a script to update versions easily
* use `QtQuick 2.0` everywhere instead of `QtQuick 2.X`
I'm not sure about this. What do you think?

**Comment by plfiorini** [comment]
Keep `QtQuick 2.0` and bump the import version when you really need (e.g. a new API added in later version, check `since` in the documentation).

**Comment by timsueberkrueb** [comment]
Moving this to `TODO`.

**Comment by timsueberkrueb** [comment]
Will be done right after merging `feature/qtwebengine`.

**Comment by timsueberkrueb** [comment]
`feature/qtwebengine` was merged. Is there a script I can use to easily change QML import versions?

**Comment by plfiorini** [comment]
`find . -type f -name "*.qml" | xargs perl -p -i -e 's@old@new@g'`

replace `old` with the old import and `new` with the new import.

**Comment by plfiorini** [comment]
Beware that `import QtQuick 2.0` might not be good if you are using something that is available only in later versions.

**Comment by timsueberkrueb** [comment]
Thank you, @plfiorini!
