### ISSUE TITLE
Consider providing an AppImage

### ISSUE THREAD

**Issue by timsueberkrueb** [lirios/browser#44]
As suggested by @probonopd we should consider to provide AppImage packages.

Living list of things to think about:
* Automatic builds?

I haven't looked into AppImage yet, contributions are very welcome!

--- 
Would you be interested in an [AppImage](http://appimage.org/)? Shouldn't be too hard using [linuxdeployqt](https://github.com/probonopd/linuxdeployqt). Let me know if you'd like help.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

---

@probonopd's comment

**Comment by probonopd** [comment]
[Many projects](https://github.com/probonopd/linuxdeployqt#projects-using-linuxdeployqt) use a combination of [Travis CI](https://travis-ci.org/) and [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) to provide continuous builds of their application in AppImage format. This means that for evey `git push`, a version gets built and uploaded.

For this to happen, could you give me instructions on how to build this on an Ubuntu 14.04 machine? (Ideally a script that contains all the qmake, make... commands also for all the dependencies that are not part of Ubuntu). Then I can write a matching `.travis.yml` script.

**Comment by plfiorini** [comment]
@probonopd How does AppImage handle common libraries such as Qt + Fluid (our UI toolkit), is it possible to share it between applications the way you do with Flatpak runtimes?

**Comment by timsueberkrueb** [comment]
@probonopd I fear that's not that easy on Ubuntu 14.04 since we require Qt >= 5.8. There's a detailed [development guide on the wiki](https://github.com/lirios/browser/wiki/Development-Setup).

**Comment by probonopd** [comment]
AppImage is just a self-mounting filesystem that executes whatever you put inside. So the answer is "it depends":

* If you care about running these applications only on LiriOS, then you do not need to bundle Qt + Fluid, and just assume that the system provides them (where they can be managed by a traditional package manager)
* If you want your application to run on as many systems as possible, then you should bundle Qt + Fluid inside the AppImage, since we cannot assume these to be present on most target systems (distributions) out there in a recent enough version

**Comment by plfiorini** [comment]
@tim-sueberkrueb probably it would be better to use Arch binaries (until we buy a better build server and can make our binaries and recycle them between Flatpak, AppImage and Snap). On several projects we already have a Travis CI using ArchTravis so we bypass the limited Ubuntu distro they provide out of the box.

**Comment by probonopd** [comment]
> @probonopd I fear that's not that easy on Ubuntu 14.04 since we require Qt >= 5.8. 

That is no problem, check for example https://github.com/jeena/FeedTheMonkey/blob/master/.travis.yml which also needs Qt 5.8.

> There's a detailed development guide on the wiki.

> The following modules and their dependencies are required:
> 
> Fluid from develop branch
> SlimeEngine
> with either Oxide or QtWebEngine

Could you update README.md with the actual commands to fulfill these needs? That would help a lot.

**Comment by probonopd** [comment]
> probably it would be better to use Arch binaries (until we buy a better build server and can make our binaries and recycle them between Flatpak, AppImage and Snap)

I don't think so - binaries built on Arch require the latest versions of everything. What you want is actually the reverse thing, you want to build on the oldest system on which your code still can be built; that way you get binaries that run on more than just the very latest target systems (distributions). Again, if you worry only about the latest version of Liri OS and are not interested in running your application on other target systems, then this is not a concern.

**Comment by plfiorini** [comment]
@probonopd so maybe a CentOS 7 container to build the binaries would do

**Comment by probonopd** [comment]
Yes, that would be a good choice. Linus' [Subsurface](https://subsurface-divelog.org/) application, for example, uses even CentOS 6. A more pragmatic approach would be Ubuntu 14.04 on [Travis CI](https://travis-ci.org/).

**Comment by plfiorini** [comment]
@probonopd Fluid can be built as follows:

```sh
git clone -b develop https://github.com/lirios/fluid
cd fluid
mkdir build
cd build
qmake CONFIG+=use_qt_paths ..
make
sudo make install
```

slime:

```sh
git clone https://github.com/tim-sueberkrueb/slime-engine
cd slime-engine
qmake && make
sudo make install
```

browser:

```sh
mkdir build
cd build
qmake CONFIG+=use_qt_paths CONFIG+=QTWEBENGINE_ENABLED ..
make
make install
```

EDIT: added slime engine

**Comment by probonopd** [comment]
Work-in-progress here:
https://github.com/probonopd/browser/blob/patch-1/.travis.yml

Build logs can be seen on 
https://travis-ci.org/probonopd/browser/builds/

**Comment by plfiorini** [comment]
@tim-sueberkrueb btw later we can upload it to a bintray repo we already have containers and the CI binaries there

**Comment by probonopd** [comment]
Cool, you are using Bintray, that makes it super simple to enable binary delta updates...
https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information

Check
https://www.youtube.com/watch?v=FqVAtHdK1N0

**Comment by timsueberkrueb** [comment]
Just added the new icon by @crutchcorn and a desktop file.

**Comment by probonopd** [comment]
@tim-sueberkrueb how did you know, just was about to complain about the lack of a desktop file :-) Next up: an [AppStream metainfo file](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) ;-)

**Comment by probonopd** [comment]
Now getting

```
In file included from ../src/core/extensions/extensionsmanager.cpp:24:0:
../src/core/extensions/extensionsmanager.h:32:27: fatal error: quazip/quazip.h: No such file or directory
 #include <quazip/quazip.h>
```
after having merged the branch that includes the desktop file... :-(

**Comment by timsueberkrueb** [comment]
@probonopd you merged `feature/extensions_base`. The desktop file is also in `develop`.

**Comment by timsueberkrueb** [comment]
@probonopd `feature/extensions_base` requires QuaZIP: http://quazip.sourceforge.net/

**Comment by pierremtb** [comment]
Glad to have you here @probonopd ! Good work with linuxdeployqt, I ran on it last week. 
We'll need help with Calculator too :)

**Comment by pierremtb** [comment]
When I tried it last week, it worked on too different Ubuntu distros, but not on @plfiorini 's Arch

**Comment by probonopd** [comment]
> Glad to have you here @probonopd ! Good work with linuxdeployqt, I ran on it last week.
We'll need help with Calculator too :)

Let's do this one first, and then see about Calculator - I hope you can figure it out if you have a working  "template" :-)

> When I tried it last week, it worked on too different Ubuntu distros, but not on @plfiorini 's Arch

What was not working? Can you open an issue there?

**Comment by probonopd** [comment]
"SlimeEngine" does not get installed into the correct `$PREFIX`:

https://travis-ci.org/probonopd/browser/builds/212669844#L1062-L1067

It should not install stuff to `../appdir/opt/qt58` but to `../appdir/usr/...`

```
$ sudo make INSTALL_ROOT=../appdir install ; sudo chown -R $USER ../appdir ; find ../appdir/
cd modules/SlimeEngine/ && ( test -e Makefile || /opt/qt58/bin/qmake -o Makefile /home/travis/build/probonopd/browser/slime-engine/modules/SlimeEngine/SlimeEngine.pro PREFIX=/usr ) && make -f Makefile install
make[1]: Entering directory `/home/travis/build/probonopd/browser/slime-engine/modules/SlimeEngine'
install -m 644 -p /home/travis/build/probonopd/browser/slime-engine/modules/SlimeEngine/qmldir ../appdir/opt/qt58/qml/SlimeEngine/
cp -f -R /home/travis/build/probonopd/browser/slime-engine/modules/SlimeEngine/0.2 ../appdir/opt/qt58/qml/SlimeEngine/
make[1]: Leaving directory `/home/travis/build/probonopd/browser/slime-engine/modules/SlimeEngine'
```

**Comment by timsueberkrueb** [comment]
@probonopd SlimeEngine doesn't respects `PREFIX`, let me fix.

**Comment by timsueberkrueb** [comment]
@probonopd done.

**Comment by probonopd** [comment]
@tim-sueberkrueb still doesn't end up in `/usr/lib/x86_64-linux-gnu/qt5/qml/` but seemingly in `/usr/SlimeEngine` which doesn't feel quite right either. Maybe this is a case for `CONFIG+=use_qt_paths`?

**Comment by probonopd** [comment]
Right now linuxdeployqt fails to deploy it with

```
Log: Deploying QML import "SlimeEngine"
Log:   Skip import: name or path is empty
```

**Comment by probonopd** [comment]
Now I am getting

```
me@host:~$ chmod a+x liri-browser-git.30deaad-x86-64.appimage 
me@host:~$ ./liri-browser-git.30deaad-x86-64.appimage 
QQmlApplicationEngine failed to load component
qrc:/ui/Main.qml:40 Type BrowserWindow unavailable
qrc:/ui/window/BrowserWindow.qml:35 Type TabController unavailable
qrc:/ui/tabview/TabController.qml:29 Type TabBar unavailable
qrc:/ui/tabview/TabBar.qml:100 Type TabBarActionBar unavailable
qrc:/ui/tabview/TabBarActionBar.qml:27 Type ActionBar unavailable
qrc:/ui/components/ActionBar.qml:47 Type IconButton unavailable
file:///tmp/.mount_M0sbrW/usr/qml/Fluid/Controls/IconButton.qml:34 Type Icon unavailable
file:///tmp/.mount_M0sbrW/usr/qml/Fluid/Controls/Icon.qml:18 module "QtGraphicalEffects" is not installed
```
Do you know where these things normally are supposed to come from?

**Comment by plfiorini** [comment]
Missing qtgraphicaleffects pkg. You Aldo need qtsvg and qtwayland btw

**Comment by probonopd** [comment]
There is no qt58wayland in https://launchpad.net/~beineri/+archive/ubuntu/opt-qt58-trusty

**Comment by probonopd** [comment]
Check out https://transfer.sh/1wEhR/liri-browser-git.6b99833-x86-64.appimage, it is running on my Ubuntu 16.04 system. Further fine-tuning may be needed for other systems. Feedback welcome.

**Comment by probonopd** [comment]
Looks like I need to manually copy in `usr/qml/Fluid/Controls/icons` since this seemingly doesn't get installed automatically? But where can I get them from?

Getting lots of 

```
file:///home/me/squashfs-root/usr/qml/Fluid/Controls/Icon.qml:147:5: QML Image: Failed to get image from provider: image://fluidicons/action/settings
file:///home/me/squashfs-root/usr/qml/Fluid/Controls/Icon.qml:147:5: QML Image: Failed to get image from provider: image://fluidicons/file/file_download
file:///home/me/squashfs-root/usr/qml/Fluid/Controls/Icon.qml:147:5: QML Image: Failed to get image from provider: image://fluidicons/action/find_in_page
(...)
```

Any hints appreciated.

**Comment by Aldrog** [comment]
> Check out https://transfer.sh/1wEhR/liri-browser-git.6b99833-x86-64.appimage, it is running on my Ubuntu 16.04 system. Further fine-tuning may be needed for other systems. Feedback welcome.

Gives me 
```
./liri-browser-git.6b99833-x86-64.appimage: /tmp/.mount_e8Ttlh/usr/bin/../lib/libnssutil3.so: version `NSSUTIL_3.24' not found (required by /usr/lib/libnss3.so)
```
on Arch

**Comment by timsueberkrueb** [comment]
@probonopd After cloning and `cd`ing into fluid, run `./scripts/fetch_icons.sh`.
I get the same error as @Aldrog on Ubuntu 16.04.

**Comment by timsueberkrueb** [comment]
~~@plfiorini the new `qmake` doesn't seem to install the icons. I just checked locally.~~

**Comment by timsueberkrueb** [comment]
~~@plfiorini or do we need to run `fetch_icons` additionally?~~

**Comment by timsueberkrueb** [comment]
My fault. Need to run `./scripts/fetch_icons.sh`.

**Comment by probonopd** [comment]
@tim-sueberkrueb where do the icons get deployed in a regular installation?

**Comment by probonopd** [comment]
@Aldrog @tim-sueberkrueb please try:

```
./liri-browser-git.6b99833-x86-64.appimage --appimage-extract
rm squashfs-root/usr/lib/libnssutil3.so 
./squashfs-root/AppRun 
```

Does it run now on your system?

**Comment by probonopd** [comment]
Yay, the icons are there now:

![screenshot from 2017-03-19 19-04-17](https://cloud.githubusercontent.com/assets/2480569/24083430/ed6d8b7a-0cd6-11e7-9ab2-cac84df8f0a3.png)

This is on a stock Ubuntu 16.04.

**Comment by probonopd** [comment]
The icon in the dock is not the application icon on Ubuntu:

![screenshot from 2017-03-19 19-06-20](https://cloud.githubusercontent.com/assets/2480569/24083444/2a6d5e74-0cd7-11e7-987c-66364ee14742.png)

This is easy to fix, please use something along these lines to load the icon ([example](https://github.com/probonopd/QtQuickApp/blob/master/main.cpp)):

```
QGuiApplication::setWindowIcon(QIcon(app.applicationDirPath() + "/../share/pixmaps/myapplicationicon.png"));
```

**Comment by timsueberkrueb** [comment]
> where do the icons get deployed in a regular installation?

`<install-path>/Fluid/Controls/icons`

> Does it run now on your system?

yes, great!

**Comment by timsueberkrueb** [comment]
hmm, not sure why [this](https://github.com/lirios/browser/blob/develop/src/main/main.cpp#L51) doesn't work ...

**Comment by probonopd** [comment]
Good question...

**Comment by timsueberkrueb** [comment]
hmm, it works when I test it locally, but I also have the desktop file installed. Let me remove that.

**Comment by timsueberkrueb** [comment]
Doesn't work locally either, actually. So not the AppImage's fault.

**Comment by timsueberkrueb** [comment]
@probonopd should work now :)

**Comment by probonopd** [comment]
PR sent: https://github.com/lirios/browser/pull/45

**Comment by timsueberkrueb** [comment]
@probonopd wow, thank you so much <3 Are you okay with squashing the commits?

**Comment by timsueberkrueb** [comment]
The AppImage works flawlessly for me now (including the icons + icon in launcher).

**Comment by probonopd** [comment]
> The AppImage works flawlessly for me now (including the icons + icon in launcher).

Great to hear that!

> Are you okay with squashing the commits?

Yes, sure! Like I wrote in the PR :-)
