### ISSUE TITLE
Add "start with previously opened tabs" option

### ISSUE THREAD

**Issue by PoisonousJohn** [lirios/browser#50]
Nice to have feature is to start with tabs opened in previous session

**Comment by timsueberkrueb** [comment]
Yeah! Alternative option/in addition to #27.

**Comment by PoisonousJohn** [comment]
#27 is about new tab content, this feature is about starting new browser instance (session)

**Comment by timsueberkrueb** [comment]
@JohnPoison yeah, you're right, not really related. Besides of that a new dashboard could be opened on start vs. all tabs from last session could be restored.

**Comment by timsueberkrueb** [comment]
Done.
