### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by Suburbanno** [lirios/browser#57]
Windows build?  how to?

**Comment by timsueberkrueb** [comment]
Hey @Suburbanno. There's no release, yet.
We haven't looked into building for Windows yet, however [we plan to](https://github.com/lirios/browser/issues/24).
For building on your GNU/Linux distro, please see [this wiki page](https://github.com/lirios/browser/wiki/Development-Setup), which is slightly outdated, though. Basically, you can skip the `SlimeEngine` step now and there's no need for `CONFIG+=QTWEBENGINE_ENABLED` anymore.

**Comment by timsueberkrueb** [comment]
There is now information about how to build the browser on Windows. Please refer to my comment here: https://github.com/lirios/browser/issues/24#issuecomment-307570005.

**Comment by ioc2e3** [comment]
Here ( https://github.com/lirios/browser/releases ) ...

No release?

Or ...

is there no Windows version?

.
