### ISSUE TITLE
CI build broken

### ISSUE THREAD

**Issue by plfiorini** [lirios/browser#63]
With the last commit I accidentally broke the build due to a higher qbs requirement:

https://travis-ci.org/lirios/browser/builds/275744329?utm_source=email&utm_medium=notification

Maybe an update to Qt 5.9.0 will fix this. This issue is just a reminder.

**Comment by timsueberkrueb** [comment]
> Maybe an update to Qt 5.9.0 will fix this

@plfiorini yep, looks like it. The [Qt 5.9.1 for /opt Xenial](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt591-xenial/+packages) ppa seems to contain `qt59qbs` (`v1.8.1`).

**Comment by timsueberkrueb** [comment]
The problem with Qt 5.9.1 however is #62 ... probably better than broken CI builds, though.

**Comment by plfiorini** [comment]
@tim-sueberkrueb Nope a buggy Qt should not go into the appimage bundle, I can revert my patch.

**Comment by timsueberkrueb** [comment]
@plfiorini okay. I would like to see the fix for this Qt bug to land in Qt 5.9.2. The patch seems to be "in review" since end of July though.

**Comment by plfiorini** [comment]
@tim-sueberkrueb yeah :/
