### ISSUE TITLE
Incompatibility with latest Fluid changes

### ISSUE THREAD

**Issue by NyxCode** [lirios/browser#64]
After installing `liri-browser` through the [arch user repository](https://aur.archlinux.org/packages/liri-browser-git/), I get the following error when I try to start `liri-browser`:
```
QQmlApplicationEngine failed to load component
qrc:/ui/Main.qml:48 Type BrowserWindow unavailable
qrc:/ui/window/BrowserWindow.qml:390 Type DrawerDownloadsContent unavailable
qrc:/ui/drawer/content/downloads/DrawerDownloadsContent.qml:41 Type DownloadItemDelegate unavailable
qrc:/ui/drawer/content/downloads/DownloadItemDelegate.qml:31 BaseListItem is not a type

ASSERT failure in QList<T>::operator[]: "index out of range", file /usr/include/qt/QtCore/qlist.h, line 549
Abgebrochen (Speicherabzug geschrieben)
```
Then, the application exits with `134`

**Comment by timsueberkrueb** [comment]
Hey @NyxCode, thanks for reporting.
Looks like [BaseListItem has been removed from Fluid](https://github.com/lirios/fluid/commit/88f493fc59419a7af6af66004dd67f95d1bac67f). Note that this not a stable package as it is directly built and published from git so breakage like this might happen from time to time.
