### ISSUE TITLE
Ctrl + Shift + Tab

### ISSUE THREAD

**Issue by ShalokShalom** [lirios/browser#66]
Implement the mentioned key combination to move one tab to the left :smiley:

**Comment by timsueberkrueb** [comment]
This is already [implemented](https://github.com/lirios/browser/blob/974ce54fc07ab866951f6d106f1537c3cf80ac5f/src/ui/window/ShortcutManager.qml#L112). @ShalokShalom is it not working for you? Are you using a Mac?

**Comment by ShalokShalom** [comment]
Linux.

**Comment by timsueberkrueb** [comment]
@ShalokShalom and `Ctrl+Shift+Tab` not working for you? Are you sure you haven't mapped the combination somewhere else in your desktop or something like that?

**Comment by ShalokShalom** [comment]
Its working in Opera and all the other browsers. KaOS, Qt 5.9.1 and Liri-Browser 0.3.127

**Comment by timsueberkrueb** [comment]
Is `Ctrl+Tab` working?

**Comment by timsueberkrueb** [comment]
```qml
// touch test.qml
import QtQuick 2.5

Item {
    Shortcut {
        sequence: "Ctrl+Shift+Tab"
        onActivated: console.log("Ctrl+Shift+Tab pressed")
    }
}
// qmlscene test.qml
```
Does this print anything in the console?

**Comment by ShalokShalom** [comment]
Yes, Ctrl+Tab is working.

**Comment by ShalokShalom** [comment]
It prints a white screen

![screenshot_20170929_174954](https://user-images.githubusercontent.com/6344099/31024212-a25722da-a53e-11e7-8446-51a3517d177e.png)

**Comment by timsueberkrueb** [comment]
@ShalokShalom that's fine :) Does it print `Ctrl+Shift+Tab pressed` to the console when you press the combination?

**Comment by ShalokShalom** [comment]
Yes.

**Comment by timsueberkrueb** [comment]
Just pushed a commit that might fix it.

**Comment by timsueberkrueb** [comment]
The shortcut's context was set to `Qt.ApplicationShortcut` but that *should* not be a problem (unless with multiple windows).

**Comment by timsueberkrueb** [comment]
Okay, can you [try the latest AppImage](https://transfer.sh/iA7WI/Liri_Browser-git.54a5ec6-x86_64.AppImage) to check whether it's fixed? Thanks a lot!

**Comment by ShalokShalom** [comment]
I build by myself and it works. :smile: 

Thanks a lot dude ^-^
