### ISSUE TITLE
Dynamically adjust tab width

### ISSUE THREAD

**Issue by ShalokShalom** [lirios/browser#67]
My tab bar is already confusing, with about 10 tabs open. Small tabs can fix that (auto-adjustment)

**Comment by timsueberkrueb** [comment]
This is a design decision. There are multiple ways to handle many tabs. Chrome for example just continues to shrink tabs even if you can't really distinguish them anymore in the end. 
Liri currently has a fixed tab width but allows you to scroll through the row of tabs instead. 
I think that we should definitely reduce the tab width dynamically when there are many tabs but continue to rely on scrolling. This is how Firefox does it, too and I think it is the best compromise from a usability point of view.

**Comment by ShalokShalom** [comment]
I like it in Opera.

![screenshot_20170929_173308](https://user-images.githubusercontent.com/6344099/31023503-4f9be32a-a53c-11e7-910b-76a332ce5f90.png)

**Comment by timsueberkrueb** [comment]
@ShalokShalom yeah, this is pretty much what Chrome is doing, too. I don't like it to be honest. I prefer to scroll my way through the tabs while always seeing the full tab titles rather than having to hover over/click on each tab to find the one I'm actually looking for.

**Comment by ShalokShalom** [comment]
Adjustable?

**Comment by ShalokShalom** [comment]
I think also, a nice tab overview like in Opera makes sense:
https://blogs.opera.com/desktop/2015/03/opera-developer-tab-cycling-and-improved-tab-menu/

**Comment by timsueberkrueb** [comment]
@ShalokShalom how do you switch between tabs when you have so many tabs opened? Do you hover above them? Do you use the tab menu? Do you click through them?

There are several things we'd have to take into consideration:
* Hovering tabs should show a preview of the website
* Touch screen support is problematic with very small tabs
* What is the behavior when there is no favicon
* Theme color support might interfere -> icon visibility/distinguishability varies

**Comment by ShalokShalom** [comment]
Tab preview is one of those things, who let me think "who does anybody profit from that" since it breaks my focus, when I hover over the tabs. 

I simply know them by mind, mostly. The mentioned tab menu can help also, yes. 
Tab grouping can help too. 

About touch support and this feature in general: You can make it optional. 

Can you spend me an example about any page without a favicon?

This here is the official dark theme in Opera, it works here too, why not in Liri?

**Comment by timsueberkrueb** [comment]
@ShalokShalom we can have a long discussion about this but in general I would like to avoid too many options because they always come with a maintenance burden (which we learned the hard way with the old browser). That being said, I really appreciate the feedback and if this turns out to be an essential feature for many users we can of course add an option (given someone will implement it) or even make it default.
For now, we will try to improve our current design (e.g. by dynamically adjusting the tab width to use the space more effectively).

**Comment by timsueberkrueb** [comment]
https://github.com/lirios/browser/commit/f397abae7326dc88428d587c1c8918ba2c9ade34 implements the mentioned dynamic tab widths.
