### ISSUE TITLE
File uploading support

### ISSUE THREAD

**Issue by PoisonousJohn** [lirios/browser#82]
If you try upload a file to any website you'll get a crash. I believe it's not implemented yet. So it's a bug and a lack of a feature in the same time.

This is essential for the first release.

**Comment by timsueberkrueb** [comment]
@PoisonousJohn I cannot reproduce this issue here on Ubuntu 17.10 with Qt 5.10 on `develop`.
Tested it with Google Drive and Twitter.

**Comment by timsueberkrueb** [comment]
@PoisonousJohn any update? Can anyone else reproduce this? What environment (OS, Qt version) did you use?
EDIT: Cannot reproduce on Ubuntu 18.04 with Qt 5.10 and Qt 5.11.

**Comment by PoisonousJohn** [comment]
@timsueberkrueb it was under archlinux

**Comment by PoisonousJohn** [comment]
@timsueberkrueb strange, can't reproduce it either. Closed.
