### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by tim-sueberkrueb** [lirios/browser#9]
The browser should have a good selection of shortcuts.

**Comment by pierremtb** [comment]
Definitely.
And it would be nice if the main key could be different on some systems (like Command on macOS).
I like Chrome's shortcuts, haven't checked Firefox for a while though.

**Comment by PoisonousJohn** [comment]
work in progress
#30

**Comment by timsueberkrueb** [comment]
@JohnPoison thanks very much for your contribution.

**Comment by timsueberkrueb** [comment]
Some shortcuts are yet to be done:
* [x] Find in page (Ctrl+F)
* [x] New window
* [x] New private window ?

Other tasks:
* [x] "Meta+Shift+Tab" needs to be confirmed on macOS
* ~~Implement "Ctrl+l" for macOS~~

**Comment by PoisonousJohn** [comment]
I can also implement missing shortcuts. Do I need to create a different branch for it?

**Comment by timsueberkrueb** [comment]
@JohnPoison Cool! You just have to file a new pull request.
Some features are not implemented yet (e.g. fullscreen). Shortcuts for those will be implemented later.

**Comment by timsueberkrueb** [comment]
Added [an initial wiki page about shortcuts](https://github.com/lirios/browser/wiki/Help-Shortcuts).

**Comment by PoisonousJohn** [comment]
@tim-sueberkrueb for mac os x it's Cmd+L in Google Chrome, every reference to Ctrl in shortcuts is replaced to Cmd, so it should be ok for mac users

**Comment by timsueberkrueb** [comment]
@JohnPoison this can be closed now, right?

**Comment by PoisonousJohn** [comment]
@tim-sueberkrueb Yes, I think

**Comment by timsueberkrueb** [comment]
Great, thanks :)
