### ISSUE TITLE
Liri Documentation Link Broken

### ISSUE THREAD

**Issue by samarth-ramesh** [lirios/browser#93]
the link to the documentation at [https://liri-dev.readthedocs.io/en/latest/modules/browser/ ](https://liri-dev.readthedocs.io/en/latest/modules/browser/) appears to be broken. The entire subdomain appears to 404 for me.

**Comment by i2** [comment]
I wanted to again bring this to attention. T whole domain is 404!

**Comment by plfiorini** [comment]
The new link is https://docs.liri.io/modules/browser/

**Comment by samarth-ramesh** [comment]
Thanks!

________________________________________
